#!/usr/bin/env python3
"""
Idempotent install of NotNativeMemory hooks into NotNativeAgent.

NNA has a native event bus with a drop-in hook loader. This script
copies the hook directory (manifest + Python scripts + hooks.env)
into ~/.nna/hooks/notnative-memory/ where NNA discovers it at startup.

Usage:
    python merge_hooks.py <install_path> [mcp_url]

Arguments:
    install_path  - Absolute path to the NotNativeMemory install
                    directory. Used to resolve script paths in the
                    manifest and generate hooks.env.
    mcp_url       - MCP server URL. Default: http://127.0.0.1:9500/mcp
"""

import datetime
import json
import os
import shutil
import sys


def _hooks_dir() -> str:
    """Resolve ~/.nna/hooks/ across platforms."""
    if sys.platform == "win32":
        home = os.environ.get("USERPROFILE", os.path.expanduser("~"))
    else:
        home = os.path.expanduser("~")
    return os.path.join(home, ".nna", "hooks")


def _write_hooks_env(target_dir: str, mcp_url: str) -> None:
    """Write hooks.env so hook scripts know where to connect."""
    env_file = os.path.join(target_dir, "hooks.env")
    env_content = (
        "# NotNativeMemory hook configuration (NotNativeAgent)\n"
        "# Generated by the installer. Do not edit manually"
        " - re-run the installer to update.\n"
        f"MEMORY_MCP_URL={mcp_url}\n"
        "\n# Authentication.\n"
        "# The MCP server requires auth since Phase 5. Two options:\n"
        "#\n"
        "#   Option 1 (recommended): mint a Bearer token via the /tokens\n"
        "#   page in the web GUI or POST /auth/login, and paste it here:\n"
        "#       MEMORY_MCP_TOKEN=nnm_<lookup>.<secret>\n"
        "#\n"
        "#   Option 2 (single-user local only): leave MEMORY_MCP_TOKEN\n"
        "#   blank and set MEMORY_AUTH_LOCALHOST_BYPASS=1 plus\n"
        "#   MEMORY_AUTH_LOCALHOST_USER=<username> in the SERVER's .env.\n"
        "#   Only works when the server binds loopback and the hook runs\n"
        "#   on the same host.\n"
        "MEMORY_MCP_TOKEN=\n"
        "\n# UserPromptSubmit (user_prompt_inject.py)\n"
        "MEMORY_PROMPT_THRESHOLD=0.45\n"
        "MEMORY_PROMPT_HIGH_THRESHOLD=0.35\n"
        "MEMORY_PROMPT_MAX_RESULTS=3\n"
        "MEMORY_PROMPT_MIN_CHARS=15\n"
        "\n# SessionStart (session_start.py)\n"
        "MEMORY_SESSION_MAX_TOKENS=600\n"
        "\n# PreCompact (compact_guard.py)\n"
        "MEMORY_COMPACT_MAX_RESULTS=5\n"
        "\n# TurnAnalysis (turn_analysis.py — extraction + promise detection)\n"
        "MEMORY_EXTRACT_MIN_LENGTH=30\n"
        "MEMORY_EXTRACT_TEMP=0.1\n"
        "MEMORY_EXTRACT_MAX_RESULTS=5\n"
        "MEMORY_EXTRACT_TIMEOUT=10\n"
        "# Output budget for the analyzer LLM. 16000 lets reasoning models\n"
        "# (Qwen3-think, DeepSeek-R1, etc.) burn tokens on hidden CoT and\n"
        "# still emit the final JSON. Lower this for cost-sensitive cloud setups.\n"
        "MEMORY_EXTRACT_MAX_TOKENS=16000\n"
        "\n# Local OpenAI-compat LLM endpoint. Defaults to LM Studio on the\n"
        "# same host; change to a different host or Ollama's port as needed.\n"
        "OPENAI_BASE_URL=http://127.0.0.1:1234/v1\n"
        "OPENAI_API_KEY=lm-studio\n"
        "# MEMORY_EXTRACT_MODEL=  # blank = auto-discover via /v1/models\n"
        "\n# Scope for analyzer-stored memories. Must be a writable scope:\n"
        "# '_global', '_domain_<name>', or an absolute path. The server-side\n"
        "# default 'general' is rejected, so this MUST be a valid target.\n"
        "MEMORY_EXTRACT_PROJECT=_global\n"
        "\n# Skip the hidden <think> phase on reasoning-model backends.\n"
        "# Reasoning is wasted compute for a classifier prompt and burns the\n"
        "# subprocess timeout. No-op on the Anthropic Messages backend.\n"
        "MEMORY_EXTRACT_DISABLE_REASONING=1\n"
        "\n# PreToolUse safety gate (pre_tool_safety.py)\n"
        "# Disabled by default. Set =1 to refuse destructive ops like\n"
        "# `git push --force`, `rm -rf /`, `git reset --hard origin/...`.\n"
        "MEMORY_SAFETY_GATE_ENABLED=0\n"
    )
    with open(env_file, "w", encoding="utf-8") as f:
        f.write(env_content)
    print(f"  Saved hooks.env (MCP URL: {mcp_url})")


def _copy_manifest(source_dir: str, target_dir: str) -> None:
    """Copy manifest.json from the repo bundle into the install dir.

    The repo's manifest.json is the single source of truth for subscriptions
    and timeouts. Previously this function hardcoded a manifest that drifted
    away from the JSON on disk; copying eliminates that drift.
    """
    src = os.path.join(source_dir, "manifest.json")
    dst = os.path.join(target_dir, "manifest.json")
    if not os.path.exists(src):
        raise FileNotFoundError(f"manifest.json missing from bundle: {src}")
    shutil.copy2(src, dst)
    print("  Copied manifest.json")


def _write_version(target_dir: str, install_path: str) -> None:
    """Stamp install timestamp + source repo path so drift is diagnosable.

    Matches the VERSION marker the Claude bundle writes. Lets us tell at
    a glance which repo checkout produced a given installed copy.
    """
    version_file = os.path.join(target_dir, "VERSION")
    normalized = install_path.replace(chr(92), "/")
    with open(version_file, "w", encoding="utf-8") as fh:
        fh.write(f"installed_at={datetime.datetime.now().isoformat(timespec='seconds')}\n")
        fh.write(f"source_repo={normalized}\n")


# Python scripts to copy from this directory into the target
_SCRIPTS = [
    "user_prompt_inject.py",
    "session_start.py",
    "compact_guard.py",
    "turn_analysis.py",
    "pre_tool_safety.py",
]

# Files to retire from prior installs (script removed from this bundle;
# logic migrated to NNA proper per contract §5).
_RETIRED_SCRIPTS = [
    "promise_detector.py",
]

# Files to remove from the target during install (clean up after renames).
# Both the legacy script and its log file are dropped on first install
# after the turn_extractor → turn_analysis rename (2026-04-26).
_OBSOLETE_FILES = [
    "turn_extractor.py",
]


def merge(install_path: str, mcp_url: str = "http://127.0.0.1:9500/mcp"):
    """Install NotNativeMemory hooks into NNA's drop-in directory."""
    if not install_path:
        raise ValueError("install_path cannot be empty")

    hooks_base = _hooks_dir()
    target_dir = os.path.join(hooks_base, "notnative-memory")
    os.makedirs(target_dir, exist_ok=True)

    source_dir = os.path.join(install_path, "hook_bundles", "nna", "notnative-memory")

    changes_made = 0

    # Copy Python scripts
    for script in _SCRIPTS:
        src = os.path.join(source_dir, script)
        dst = os.path.join(target_dir, script)
        if os.path.exists(src):
            shutil.copy2(src, dst)
            changes_made += 1
            print(f"  Copied {script}")
        else:
            print(f"  Warning: {script} not found in {source_dir}", file=sys.stderr)

    # Copy bundle-local _internal/ package (turn_analysis_core, etc.).
    src_internal = os.path.join(source_dir, "_internal")
    dst_internal = os.path.join(target_dir, "_internal")
    if os.path.isdir(src_internal):
        os.makedirs(dst_internal, exist_ok=True)
        for entry in os.listdir(src_internal):
            if entry == "__pycache__" or entry.startswith("."):
                continue
            src_path = os.path.join(src_internal, entry)
            dst_path = os.path.join(dst_internal, entry)
            if os.path.isfile(src_path):
                shutil.copy2(src_path, dst_path)
                changes_made += 1
                print(f"  Copied _internal/{entry}")

    # Remove obsolete files left behind by previous installs.
    for obsolete in (*_OBSOLETE_FILES, *_RETIRED_SCRIPTS):
        path = os.path.join(target_dir, obsolete)
        if os.path.exists(path):
            try:
                os.remove(path)
                print(f"  Removed obsolete {obsolete}")
            except OSError as exc:
                print(f"  Warning: could not remove {obsolete}: {exc}", file=sys.stderr)

    # Copy manifest from the bundle (source of truth on disk).
    _copy_manifest(source_dir, target_dir)
    changes_made += 1

    # Preserve user-edited hooks.env across re-installs (matches Claude
    # bundle). Write the canonical default only when no file exists yet.
    env_file = os.path.join(target_dir, "hooks.env")
    if os.path.exists(env_file):
        print(f"  Preserved existing {env_file}")
    else:
        _write_hooks_env(target_dir, mcp_url)
    changes_made += 1

    # Stamp VERSION so drift is diagnosable.
    _write_version(target_dir, install_path)

    print(f"  Installed to {target_dir}")
    return changes_made


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python merge_hooks.py <install_path> [mcp_url]")
        sys.exit(1)

    path = sys.argv[1]
    url = sys.argv[2] if len(sys.argv) > 2 else "http://127.0.0.1:9500/mcp"
    merge(path, url)
