#!/usr/bin/env python3
"""
Idempotent merge of NotNativeMemory hooks into NotNativeCoder settings.

Reads ~/.nnc/settings.json, adds or updates the memory hook entries,
and writes back. Safe to run multiple times — identifies existing
entries by the "notnative-memory" marker in the command path and
updates them in place rather than duplicating.

Usage:
    python merge_hooks.py <install_path> [mcp_url]

Arguments:
    install_path  - Absolute path to the NotNativeMemory install directory.
                    Forward slashes recommended (works on all platforms).
    mcp_url       - Optional MCP server URL. Default: http://localhost:9500/mcp
"""

import json
import os
import sys

_HOOK_SCRIPTS = {
    "memory_inject.py": "memory_inject",
    "compact_guard.py": "compact_guard",
    "user_prompt_inject.py": "user_prompt_inject",
}

# Hook event definitions: what we want in settings.json for NNC.
# NNC's config shape is a flat map of event-name -> array of hook
# specs. Each spec has a "command" plus optional matcher/timeout_ms.
_DESIRED_HOOKS = {
    "UserPromptSubmit": {
        "script": "user_prompt_inject.py",
        "matcher": None,
        "timeout_ms": 10000,
    },
    "PreToolUse": {
        "script": "memory_inject.py",
        "matcher": "edit_file|write_file|read_file|bash",
        "timeout_ms": 10000,
    },
    "PreCompact": {
        "script": "compact_guard.py",
        "matcher": None,
        "timeout_ms": 10000,
    },
}


def _settings_path() -> str:
    """Resolve ~/.nnc/settings.json across platforms."""
    if sys.platform == "win32":
        home = os.environ.get("USERPROFILE", os.path.expanduser("~"))
    else:
        home = os.path.expanduser("~")
    return os.path.join(home, ".nnc", "settings.json")


def _is_our_hook_entry(entry) -> str:
    """
    Check if a hook entry (string or object) contains one of our scripts.
    Returns the script name if found, empty string otherwise.
    """
    if isinstance(entry, str):
        command = entry
    elif isinstance(entry, dict):
        command = entry.get("command", "")
    else:
        return ""

    for script_name in _HOOK_SCRIPTS:
        if script_name in command:
            return script_name
    return ""


def _build_hook_command(install_path: str, script_name: str) -> str:
    """Build the hook command string with the correct install path."""
    normalized = install_path.replace("\\", "/")
    return f"python {normalized}/nnc/hooks/{script_name}"


def _build_hook_spec(install_path: str, config: dict) -> dict:
    """Build a rich-form hook spec for NNC's settings.json."""
    spec = {
        "command": _build_hook_command(install_path, config["script"]),
        "timeout_ms": config["timeout_ms"],
    }
    if config.get("matcher"):
        spec["matcher"] = config["matcher"]
    return spec


def _load_settings(settings_file: str) -> dict:
    """Load settings.json, creating a backup if it has invalid JSON."""
    if not os.path.exists(settings_file):
        return {}

    with open(settings_file, "r", encoding="utf-8") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            print(f"  Warning: {settings_file} has invalid JSON. Creating backup.")
            try:
                backup = settings_file + ".bak"
                f.seek(0)
                with open(backup, "w", encoding="utf-8") as bak:
                    bak.write(f.read())
            except OSError as exc:
                print(f"  Warning: could not create backup: {exc}", file=sys.stderr)
            return {}


def _write_hooks_env(install_path: str, mcp_url: str) -> None:
    """Write hooks.env so hook scripts know where to connect."""
    hooks_dir = os.path.join(install_path, "nnc", "hooks")
    env_file = os.path.join(hooks_dir, "hooks.env")
    env_content = (
        "# NotNativeMemory hook configuration (NotNativeCoder)\n"
        "# Generated by the installer. Do not edit manually"
        " - re-run the installer to update.\n"
        f"MEMORY_MCP_URL={mcp_url}\n"
        "\n# PreToolUse (memory_inject.py)\n"
        "MEMORY_HOOK_THRESHOLD=0.55\n"
        "MEMORY_HOOK_HIGH_THRESHOLD=0.40\n"
        "MEMORY_HOOK_MAX_RESULTS=3\n"
        "\n# UserPromptSubmit (user_prompt_inject.py)\n"
        "MEMORY_PROMPT_THRESHOLD=0.45\n"
        "MEMORY_PROMPT_HIGH_THRESHOLD=0.35\n"
        "MEMORY_PROMPT_MAX_RESULTS=3\n"
        "MEMORY_PROMPT_MIN_CHARS=15\n"
        "\n# PreCompact (compact_guard.py)\n"
        "MEMORY_COMPACT_MAX_RESULTS=5\n"
    )
    with open(env_file, "w", encoding="utf-8") as f:
        f.write(env_content)
    print(f"  Saved hooks.env (MCP URL: {mcp_url})")


def merge(install_path: str, mcp_url: str = "http://localhost:9500/mcp"):
    """Merge NotNativeMemory hooks into NotNativeCoder settings."""
    if not install_path:
        raise ValueError("install_path cannot be empty")

    settings_file = _settings_path()
    os.makedirs(os.path.dirname(settings_file), exist_ok=True)

    settings = _load_settings(settings_file)

    if "hooks" not in settings:
        settings["hooks"] = {}

    changes_made = 0

    for event_name, config in _DESIRED_HOOKS.items():
        if event_name not in settings["hooks"]:
            settings["hooks"][event_name] = []

        entries = settings["hooks"][event_name]
        desired_spec = _build_hook_spec(install_path, config)

        # Look for an existing entry that's ours and replace it
        replaced = False
        for i, entry in enumerate(entries):
            if _is_our_hook_entry(entry):
                entries[i] = desired_spec
                replaced = True
                changes_made += 1
                print(f"  Updated existing {event_name} hook for {config['script']}")
                break

        if not replaced:
            entries.append(desired_spec)
            changes_made += 1
            print(f"  Added {event_name} hook for {config['script']}")

    with open(settings_file, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=2)

    if changes_made > 0:
        print(f"  Saved to {settings_file}")
    else:
        print("  No changes needed - hooks already configured")

    _write_hooks_env(install_path, mcp_url)

    return changes_made


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python merge_hooks.py <install_path> [mcp_url]")
        sys.exit(1)

    path = sys.argv[1]
    url = sys.argv[2] if len(sys.argv) > 2 else "http://localhost:9500/mcp"
    merge(path, url)
