#!/usr/bin/env python3
"""
Idempotent merge of NotNativeMemory hooks into NotNativeCoder settings.

Reads ~/.nnc/settings.json, adds or updates the memory hook entries,
and writes back. Safe to run multiple times. Identifies existing
entries by the script name in the command path and updates them in
place rather than duplicating.

Also removes hook entries we used to install but no longer do (e.g.
the old PreToolUse memory_inject hook, deprecated 2026-04-19).

Usage:
    python merge_hooks.py <install_path> [mcp_url]

Arguments:
    install_path  - Absolute path to the NotNativeMemory install
                    directory. Forward slashes recommended.
    mcp_url       - Optional MCP server URL. Default:
                    http://localhost:9500/mcp
"""

import json
import os
import sys

# Script names this installer has ever owned. Used to recognize our
# entries in settings.json for update-or-sweep.
_HOOK_SCRIPTS = {
    "memory_inject.py",       # retired 2026-04-19 (PreToolUse)
    "compact_guard.py",
    "user_prompt_inject.py",
    "session_start.py",       # added 2026-04-19
}

# Hook event definitions: what we want in settings.json right now for
# NNC. NNC's config shape is a flat map of event-name to array of hook
# specs. Each spec has a "command" plus optional matcher/timeout_ms.
_DESIRED_HOOKS = {
    "UserPromptSubmit": {
        "script": "user_prompt_inject.py",
        "matcher": None,
        "timeout_ms": 10000,
    },
    "SessionStart": {
        "script": "session_start.py",
        "matcher": None,
        "timeout_ms": 10000,
    },
    "PreCompact": {
        "script": "compact_guard.py",
        "matcher": None,
        "timeout_ms": 10000,
    },
}

_RETIRED_SCRIPTS = {
    s for s in _HOOK_SCRIPTS
    if s not in {cfg["script"] for cfg in _DESIRED_HOOKS.values()}
}


def _settings_path() -> str:
    """Resolve ~/.nnc/settings.json across platforms."""
    if sys.platform == "win32":
        home = os.environ.get("USERPROFILE", os.path.expanduser("~"))
    else:
        home = os.path.expanduser("~")
    return os.path.join(home, ".nnc", "settings.json")


def _entry_script_name(entry) -> str:
    """
    Return the NotNativeMemory script name for this hook entry, or ""
    if the entry is not ours. NNC accepts both bare command strings and
    rich-form {"command": ..., "timeout_ms": ...} objects.
    """
    if isinstance(entry, str):
        command = entry
    elif isinstance(entry, dict):
        command = entry.get("command", "")
    else:
        return ""

    for script_name in _HOOK_SCRIPTS:
        if script_name in command:
            return script_name
    return ""


def _build_hook_command(install_path: str, script_name: str) -> str:
    """Build the hook command string with the correct install path."""
    normalized = install_path.replace("\\", "/")
    return f"python {normalized}/nnc/hooks/{script_name}"


def _build_hook_spec(install_path: str, config: dict) -> dict:
    """Build a rich-form hook spec for NNC's settings.json."""
    spec = {
        "command": _build_hook_command(install_path, config["script"]),
        "timeout_ms": config["timeout_ms"],
    }
    if config.get("matcher"):
        spec["matcher"] = config["matcher"]
    return spec


def _load_settings(settings_file: str) -> dict:
    """Load settings.json, creating a backup if it has invalid JSON."""
    if not os.path.exists(settings_file):
        return {}

    with open(settings_file, "r", encoding="utf-8") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            print(f"  Warning: {settings_file} has invalid JSON. Creating backup.")
            try:
                backup = settings_file + ".bak"
                f.seek(0)
                with open(backup, "w", encoding="utf-8") as bak:
                    bak.write(f.read())
            except OSError as exc:
                print(f"  Warning: could not create backup: {exc}", file=sys.stderr)
            return {}


def _write_hooks_env(install_path: str, mcp_url: str) -> None:
    """Write hooks.env so hook scripts know where to connect."""
    hooks_dir = os.path.join(install_path, "nnc", "hooks")
    env_file = os.path.join(hooks_dir, "hooks.env")
    env_content = (
        "# NotNativeMemory hook configuration (NotNativeCoder)\n"
        "# Generated by the installer. Do not edit manually"
        " - re-run the installer to update.\n"
        f"MEMORY_MCP_URL={mcp_url}\n"
        "\n# Authentication.\n"
        "# The MCP server requires auth since Phase 5. Two options:\n"
        "#\n"
        "#   Option 1 (recommended): mint a Bearer token via the /tokens\n"
        "#   page in the web GUI or POST /auth/login, and paste it here:\n"
        "#       MEMORY_MCP_TOKEN=nnm_<lookup>.<secret>\n"
        "#\n"
        "#   Option 2 (single-user local only): leave MEMORY_MCP_TOKEN\n"
        "#   blank and set MEMORY_AUTH_LOCALHOST_BYPASS=1 plus\n"
        "#   MEMORY_AUTH_LOCALHOST_USER=<username> in the SERVER's .env.\n"
        "#   Only works when the server binds loopback and the hook runs\n"
        "#   on the same host.\n"
        "MEMORY_MCP_TOKEN=\n"
        "\n# UserPromptSubmit (user_prompt_inject.py)\n"
        "MEMORY_PROMPT_THRESHOLD=0.45\n"
        "MEMORY_PROMPT_HIGH_THRESHOLD=0.35\n"
        "MEMORY_PROMPT_MAX_RESULTS=3\n"
        "MEMORY_PROMPT_MIN_CHARS=15\n"
        "\n# SessionStart (session_start.py)\n"
        "MEMORY_SESSION_MAX_TOKENS=600\n"
        "\n# PreCompact (compact_guard.py)\n"
        "MEMORY_COMPACT_MAX_RESULTS=5\n"
    )
    with open(env_file, "w", encoding="utf-8") as f:
        f.write(env_content)
    print(f"  Saved hooks.env (MCP URL: {mcp_url})")


def _sweep_retired_hooks(settings: dict) -> int:
    """
    Remove any hook entries whose script is in _RETIRED_SCRIPTS.
    Returns the number of entries removed.
    """
    if "hooks" not in settings:
        return 0

    removed = 0
    for event_name in list(settings["hooks"].keys()):
        entries = settings["hooks"][event_name]
        if not isinstance(entries, list):
            continue

        kept = []
        for entry in entries:
            script = _entry_script_name(entry)
            if script and script in _RETIRED_SCRIPTS:
                removed += 1
                print(f"  Retired {event_name} hook for {script}")
                continue
            kept.append(entry)

        if kept:
            settings["hooks"][event_name] = kept
        else:
            del settings["hooks"][event_name]

    return removed


def merge(install_path: str, mcp_url: str = "http://localhost:9500/mcp"):
    """Merge NotNativeMemory hooks into NotNativeCoder settings."""
    if not install_path:
        raise ValueError("install_path cannot be empty")

    settings_file = _settings_path()
    os.makedirs(os.path.dirname(settings_file), exist_ok=True)

    settings = _load_settings(settings_file)

    if "hooks" not in settings:
        settings["hooks"] = {}

    # Set memoryUrl so NNC's in-process memory client knows where to
    # connect. Only overwrites if missing or different, letting users
    # override without losing it on re-install.
    if settings.get("memoryUrl") != mcp_url:
        settings["memoryUrl"] = mcp_url
        print(f"  Set memoryUrl = {mcp_url}")

    changes_made = 0
    changes_made += _sweep_retired_hooks(settings)

    for event_name, config in _DESIRED_HOOKS.items():
        if event_name not in settings["hooks"]:
            settings["hooks"][event_name] = []

        entries = settings["hooks"][event_name]
        desired_spec = _build_hook_spec(install_path, config)

        replaced = False
        for i, entry in enumerate(entries):
            if _entry_script_name(entry) == config["script"]:
                entries[i] = desired_spec
                replaced = True
                changes_made += 1
                print(f"  Updated existing {event_name} hook for {config['script']}")
                break

        if not replaced:
            entries.append(desired_spec)
            changes_made += 1
            print(f"  Added {event_name} hook for {config['script']}")

    with open(settings_file, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=2)

    if changes_made > 0:
        print(f"  Saved to {settings_file}")
    else:
        print("  No changes needed - hooks already configured")

    _write_hooks_env(install_path, mcp_url)

    return changes_made


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python merge_hooks.py <install_path> [mcp_url]")
        sys.exit(1)

    path = sys.argv[1]
    url = sys.argv[2] if len(sys.argv) > 2 else "http://localhost:9500/mcp"
    merge(path, url)
