#!/usr/bin/env python3
"""
Idempotent merge of NotNativeMemory hooks into Claude Code settings.

Reads ~/.claude/settings.json, adds or updates the memory hook
entries, and writes back. Safe to run multiple times — identifies
existing entries by the "notnative-memory" marker in the command path
and updates them in place rather than duplicating.

Also removes hook entries we used to install but no longer do (e.g.
the old PreToolUse memory_inject hook, deprecated 2026-04-19). That
lets a re-install quietly retire hooks that were structurally
mis-timed without requiring the user to edit settings.json by hand.

Usage:
    python merge_hooks.py <install_path> [mcp_url]

Arguments:
    install_path  - Absolute path to the NotNativeMemory install
                    directory. Forward slashes recommended.
    mcp_url       - Optional MCP server URL. Default:
                    http://localhost:9500/mcp
"""

import json
import os
import sys

# Script names this installer has ever owned. Used to RECOGNIZE our
# entries in settings.json — both the ones we still want and the ones
# we're removing. Keep retired scripts listed here until we're willing
# to lose the ability to auto-clean up their settings entries.
_HOOK_SCRIPTS = {
    "memory_inject.py",       # retired 2026-04-19 (PreToolUse)
    "compact_guard.py",
    "user_prompt_inject.py",
    "session_start.py",       # added 2026-04-19
}

# Hook event definitions: what we want in settings.json right now.
# Scripts in _HOOK_SCRIPTS but NOT here are swept by the retire logic.
_DESIRED_HOOKS = {
    "UserPromptSubmit": {
        "matcher": "",
        "script": "user_prompt_inject.py",
        "timeout": 10,
    },
    "SessionStart": {
        "matcher": "",
        "script": "session_start.py",
        "timeout": 10,
    },
    "PreCompact": {
        "matcher": "",
        "script": "compact_guard.py",
        "timeout": 10,
    },
}

# Scripts we've retired — any existing settings entry pointing at one
# of these gets removed during the merge. Derived from the set of
# recognized scripts that aren't currently desired.
_RETIRED_SCRIPTS = {
    s for s in _HOOK_SCRIPTS
    if s not in {cfg["script"] for cfg in _DESIRED_HOOKS.values()}
}


def _settings_path() -> str:
    """Resolve ~/.claude/settings.json across platforms."""
    if sys.platform == "win32":
        home = os.environ.get("USERPROFILE", os.path.expanduser("~"))
    else:
        home = os.path.expanduser("~")
    return os.path.join(home, ".claude", "settings.json")


def _group_script_name(group: dict) -> str:
    """
    Return the NotNativeMemory script name for this hook group, or ""
    if the group is not ours. A group is "ours" if any of its hook
    commands references one of the scripts in _HOOK_SCRIPTS.
    """
    for hook in group.get("hooks", []):
        cmd = hook.get("command", "")
        for script_name in _HOOK_SCRIPTS:
            if script_name in cmd:
                return script_name
    return ""


def _build_hook_command(install_path: str, script_name: str) -> str:
    """Build the hook command string with the correct install path."""
    normalized = install_path.replace("\\", "/")
    return f"python {normalized}/claude/hooks/{script_name}"


def _load_settings(settings_file: str) -> dict:
    """Load settings.json, creating a backup if it has invalid JSON."""
    if not os.path.exists(settings_file):
        return {}

    with open(settings_file, "r", encoding="utf-8") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            print(f"  Warning: {settings_file} has invalid JSON. Creating backup.")
            try:
                backup = settings_file + ".bak"
                f.seek(0)
                with open(backup, "w", encoding="utf-8") as bak:
                    bak.write(f.read())
            except OSError as exc:
                print(f"  Warning: could not create backup: {exc}", file=sys.stderr)
            return {}


def _write_hooks_env(install_path: str, mcp_url: str) -> None:
    """Write hooks.env so hook scripts know where to connect."""
    hooks_dir = os.path.join(install_path, "claude", "hooks")
    env_file = os.path.join(hooks_dir, "hooks.env")
    env_content = (
        "# NotNativeMemory hook configuration\n"
        "# Generated by the installer. Do not edit manually"
        " - re-run the installer to update.\n"
        f"MEMORY_MCP_URL={mcp_url}\n"
        "\n# UserPromptSubmit (user_prompt_inject.py)\n"
        "MEMORY_PROMPT_THRESHOLD=0.45\n"
        "MEMORY_PROMPT_HIGH_THRESHOLD=0.35\n"
        "MEMORY_PROMPT_MAX_RESULTS=3\n"
        "MEMORY_PROMPT_MIN_CHARS=15\n"
        "\n# SessionStart (session_start.py)\n"
        "MEMORY_SESSION_MAX_TOKENS=600\n"
        "\n# PreCompact (compact_guard.py)\n"
        "MEMORY_COMPACT_MAX_RESULTS=5\n"
    )
    with open(env_file, "w", encoding="utf-8") as f:
        f.write(env_content)
    print(f"  Saved hooks.env (MCP URL: {mcp_url})")


def _sweep_retired_hooks(settings: dict) -> int:
    """
    Remove any hook groups whose script is in _RETIRED_SCRIPTS. Returns
    the number of entries removed. Leaves groups that don't reference
    our scripts completely alone — we only touch what we installed.
    """
    if "hooks" not in settings:
        return 0

    removed = 0
    # Iterate a snapshot of event names so we can mutate the underlying
    # dict (drop empty event lists after we clean them).
    for event_name in list(settings["hooks"].keys()):
        groups = settings["hooks"][event_name]
        if not isinstance(groups, list):
            continue

        kept = []
        for group in groups:
            script = _group_script_name(group)
            if script and script in _RETIRED_SCRIPTS:
                removed += 1
                print(f"  Retired {event_name} hook for {script}")
                continue
            kept.append(group)

        if kept:
            settings["hooks"][event_name] = kept
        else:
            # Drop the event key entirely if we emptied it. Leaving an
            # empty list behind is harmless but noisy in settings.json.
            del settings["hooks"][event_name]

    return removed


def merge(install_path: str, mcp_url: str = "http://localhost:9500/mcp"):
    """Merge NotNativeMemory hooks into Claude Code settings."""
    if not install_path:
        raise ValueError("install_path cannot be empty")

    settings_file = _settings_path()
    os.makedirs(os.path.dirname(settings_file), exist_ok=True)

    settings = _load_settings(settings_file)

    if "hooks" not in settings:
        settings["hooks"] = {}

    changes_made = 0

    # 1. Sweep retired hooks FIRST so the new desired layout lands on a
    #    clean slate. Order matters: some events may have both a
    #    retired entry and a new-desired entry (e.g. if the script
    #    changed name under the same event) and sweeping first keeps
    #    the match logic simple.
    changes_made += _sweep_retired_hooks(settings)

    # 2. Upsert the currently-desired hooks.
    for event_name, config in _DESIRED_HOOKS.items():
        if event_name not in settings["hooks"]:
            settings["hooks"][event_name] = []

        hook_groups = settings["hooks"][event_name]
        desired_command = _build_hook_command(install_path, config["script"])

        found = False
        for group in hook_groups:
            if _group_script_name(group) == config["script"]:
                group["matcher"] = config["matcher"]
                group["hooks"] = [
                    {
                        "type": "command",
                        "command": desired_command,
                        "timeout": config["timeout"],
                    }
                ]
                found = True
                changes_made += 1
                print(f"  Updated existing {event_name} hook for {config['script']}")
                break

        if not found:
            hook_groups.append({
                "matcher": config["matcher"],
                "hooks": [
                    {
                        "type": "command",
                        "command": desired_command,
                        "timeout": config["timeout"],
                    }
                ],
            })
            changes_made += 1
            print(f"  Added {event_name} hook for {config['script']}")

    with open(settings_file, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=2)

    if changes_made > 0:
        print(f"  Saved to {settings_file}")
    else:
        print("  No changes needed - hooks already configured")

    _write_hooks_env(install_path, mcp_url)

    return changes_made


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python merge_hooks.py <install_path> [mcp_url]")
        sys.exit(1)

    path = sys.argv[1]
    url = sys.argv[2] if len(sys.argv) > 2 else "http://localhost:9500/mcp"
    merge(path, url)
