#!/usr/bin/env python3
"""
Idempotent merge of NotNativeMemory hooks into Claude Code settings.

Reads ~/.claude/settings.json, adds or updates the memory hook entries,
and writes back. Safe to run multiple times - identifies existing entries
by the "notnative-memory" marker in the command path and updates them
in place rather than duplicating.

Usage:
    python merge_hooks.py <install_path> [mcp_url]

Arguments:
    install_path  - Absolute path to the NotNativeMemory install directory.
                    Forward slashes recommended (works on all platforms).
    mcp_url       - Optional MCP server URL. Default: http://localhost:9500/mcp
"""

import json
import os
import sys

_HOOK_SCRIPTS = {
    "memory_inject.py": "memory_inject",
    "compact_guard.py": "compact_guard",
    "user_prompt_inject.py": "user_prompt_inject",
}

# Hook event definitions: what we want in settings.json
_DESIRED_HOOKS = {
    "UserPromptSubmit": {
        "matcher": "",
        "script": "user_prompt_inject.py",
        "timeout": 10,
    },
    "PreToolUse": {
        "matcher": "Edit|Write|Bash",
        "script": "memory_inject.py",
        "timeout": 10,
    },
    "PreCompact": {
        "matcher": "",
        "script": "compact_guard.py",
        "timeout": 10,
    },
}


def _settings_path() -> str:
    """Resolve ~/.claude/settings.json across platforms."""
    if sys.platform == "win32":
        home = os.environ.get("USERPROFILE", os.path.expanduser("~"))
    else:
        home = os.path.expanduser("~")
    return os.path.join(home, ".claude", "settings.json")


def _is_our_hook_group(group: dict) -> str:
    """
    Check if a hook group (matcher + hooks array) contains our hooks.
    Returns the script name if found, empty string otherwise.
    """
    for hook in group.get("hooks", []):
        cmd = hook.get("command", "")
        for script_name in _HOOK_SCRIPTS:
            if script_name in cmd:
                return script_name
    return ""


def _build_hook_command(install_path: str, script_name: str) -> str:
    """Build the hook command string with the correct install path."""
    normalized = install_path.replace("\\", "/")
    return f"python {normalized}/claude/hooks/{script_name}"


def _load_settings(settings_file: str) -> dict:
    """Load settings.json, creating a backup if it has invalid JSON."""
    if not os.path.exists(settings_file):
        return {}

    with open(settings_file, "r", encoding="utf-8") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            print(f"  Warning: {settings_file} has invalid JSON. Creating backup.")
            try:
                backup = settings_file + ".bak"
                f.seek(0)
                with open(backup, "w", encoding="utf-8") as bak:
                    bak.write(f.read())
            except OSError as exc:
                print(f"  Warning: could not create backup: {exc}", file=sys.stderr)
            return {}


def _write_hooks_env(install_path: str, mcp_url: str) -> None:
    """Write hooks.env so hook scripts know where to connect."""
    hooks_dir = os.path.join(install_path, "claude", "hooks")
    env_file = os.path.join(hooks_dir, "hooks.env")
    env_content = (
        "# NotNativeMemory hook configuration\n"
        "# Generated by the installer. Do not edit manually"
        " - re-run the installer to update.\n"
        f"MEMORY_MCP_URL={mcp_url}\n"
        "\n# PreToolUse (memory_inject.py)\n"
        "MEMORY_HOOK_THRESHOLD=0.55\n"
        "MEMORY_HOOK_HIGH_THRESHOLD=0.40\n"
        "MEMORY_HOOK_MAX_RESULTS=3\n"
        "\n# UserPromptSubmit (user_prompt_inject.py)\n"
        "MEMORY_PROMPT_THRESHOLD=0.45\n"
        "MEMORY_PROMPT_HIGH_THRESHOLD=0.35\n"
        "MEMORY_PROMPT_MAX_RESULTS=3\n"
        "MEMORY_PROMPT_MIN_CHARS=15\n"
        "\n# PreCompact (compact_guard.py)\n"
        "MEMORY_COMPACT_MAX_RESULTS=5\n"
    )
    with open(env_file, "w", encoding="utf-8") as f:
        f.write(env_content)
    print(f"  Saved hooks.env (MCP URL: {mcp_url})")


def merge(install_path: str, mcp_url: str = "http://localhost:9500/mcp"):
    """Merge NotNativeMemory hooks into Claude Code settings."""
    if not install_path:
        raise ValueError("install_path cannot be empty")

    settings_file = _settings_path()
    os.makedirs(os.path.dirname(settings_file), exist_ok=True)

    settings = _load_settings(settings_file)

    if "hooks" not in settings:
        settings["hooks"] = {}

    changes_made = 0

    for event_name, config in _DESIRED_HOOKS.items():
        if event_name not in settings["hooks"]:
            settings["hooks"][event_name] = []

        hook_groups = settings["hooks"][event_name]

        # Look for an existing entry that's ours
        found = False
        for group in hook_groups:
            if _is_our_hook_group(group):
                group["matcher"] = config["matcher"]
                group["hooks"] = [
                    {
                        "type": "command",
                        "command": _build_hook_command(install_path, config["script"]),
                        "timeout": config["timeout"],
                    }
                ]
                found = True
                changes_made += 1
                print(f"  Updated existing {event_name} hook for {config['script']}")
                break

        if not found:
            new_group = {
                "matcher": config["matcher"],
                "hooks": [
                    {
                        "type": "command",
                        "command": _build_hook_command(install_path, config["script"]),
                        "timeout": config["timeout"],
                    }
                ],
            }
            hook_groups.append(new_group)
            changes_made += 1
            print(f"  Added {event_name} hook for {config['script']}")

    # Write settings back
    with open(settings_file, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=2)

    if changes_made > 0:
        print(f"  Saved to {settings_file}")
    else:
        print("  No changes needed - hooks already configured")

    _write_hooks_env(install_path, mcp_url)

    return changes_made


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python merge_hooks.py <install_path> [mcp_url]")
        sys.exit(1)

    path = sys.argv[1]
    url = sys.argv[2] if len(sys.argv) > 2 else "http://localhost:9500/mcp"
    merge(path, url)
